### ISSUE TITLE
gcc 11 fix is messing with .cl files

### ISSUE THREAD

**Issue by notEvil** [bartoszek/AUR-luxcorerender-git#5]
Hi,

cuda kernels won't compile because the fix for gcc11 replaces isnan and isinf in .cl files with std::...
removing cl files with grep solves the issue
```bash
  #fix gcc:11 missing header
  grep -lRE "is(nan|inf)" "${srcdir}/${_name}"/{include,src}|grep -iv '\.cl$'|xargs sed -E 's/is(nan|inf)/std::&/g' -i
```

**Comment by bartoszek** [comment]
Thanks, I'll try to fix this shortly.
